remote_theme: pages-themes/architect@v0.2.0
title: Siming Deng
description: Intern @ Data Products LLC | Data Science Fellow @ CUNY Tech Prep | Programming, Math & Business Peer Tutor @ Baruch College | Data Analytics Student @ Baruch College
