remote_theme: pages-themes/architect@v0.2.0
title: Siming Deng
description: Accounting & Data Analyst Intern @ Smart Design | Data Science Fellow @ CUNY Tech Prep | Programming, Math & Business Peer Tutor and Data Analytics Student @ Baruch College
